#!/bin/bash

source /usr/local/emhttp/plugins/compose.manager/default.cfg
source /boot/config/plugins/compose.manager/compose.manager.cfg

COMPOSE_ROOT=$PROJECTS_FOLDER
COMPOSE_WRAPPER=/usr/local/emhttp/plugins/compose.manager/scripts/compose.sh

sanitize() {
   local s="${1?need a string}"
   s="${s// /_}"
   s="${s/./_}"
   s="${s/-/_}"
   echo "${s,,}" # convert to lowercase
}

recreate=""
if [ "$AUTOSTART_FORCE_RECREATE" = "true" ]; then
    recreate="--recreate"
fi

debug=""
if [ "$DEBUG_TO_LOG" = "true" ]; then
    debug="--debug"
fi

for dir in $COMPOSE_ROOT/*; do
    if [ -d "$dir" ]; then
        if [ -f "$dir/docker-compose.yml" ] || [ -f "$dir/indirect" ]; then
            if [ -f "$dir/autostart" ]; then
                autostart=${dir}/autostart
                if [ 'true' == "$(< "${autostart}" )" ]; then
                    name=${dir}/name
                    name=$(< "${name}")
                    name=$(sanitize ${name})
                    override=""
                    if [ -f "$dir/docker-compose.override.yml" ]; then
                        override="$dir/docker-compose.override.yml"
                        override="-f ${override@Q}"
                    fi
                    envpath=""
                    if [ -f "$dir/envpath" ]; then
                        envpath="$dir/envpath"
                        envpath="$(< "${envpath}" )"
                        envpath="-e ${envpath@Q}"
                    fi

                    retry_args=""
                    if [ -f "$dir/retry_count" ]; then
                        retry_count="$(< "$dir/retry_count")"
                        [[ "$retry_count" =~ ^[0-9]+$ ]] || retry_count="0"
                        if [ "$retry_count" -gt 0 ]; then
                            retry_wait="10"
                            if [ -f "$dir/retry_wait" ]; then
                                retry_wait="$(< "$dir/retry_wait")"
                            fi
                            [[ "$retry_wait" =~ ^[0-9]+$ ]] || retry_wait="10"
                            retry_args="-r ${retry_count@Q} -w ${retry_wait@Q}"

                            if [ -f "$dir/retry_rebuild" ]; then
                                retry_rebuild_state="$(< "$dir/retry_rebuild")"
                                if [ "$retry_rebuild_state" = "true" ]; then
                                    retry_args="$retry_args --retry-rebuild"
                                fi
                            fi
                        fi
                    fi

                    logger "Starting compose stack: ${name}"
                    if [ -f "$dir/indirect" ]; then
                        indirect=${dir}/indirect
                        indirect=$(< "${indirect}")
                        eval $COMPOSE_WRAPPER -c up -d ${indirect@Q} -p ${name} $recreate $debug $override $envpath $retry_args > /dev/null &
                    else
                        dir="$dir/docker-compose.yml"
                        eval $COMPOSE_WRAPPER -c up -f ${dir@Q} -p ${name} $recreate $debug $override $envpath $retry_args > /dev/null &
                    fi
                fi
            fi
        fi
    fi
done

wait
